### ISSUE TITLE
Upgrade to 3.1.31.1

### ISSUE THREAD

**Issue by aperfeito** [sshmanko/acestream-armv7#3]
Hi ,
  You need to upgrade for latest version

Thanks

**Comment by YaPaY** [comment]
yes. We are wating for the update

**Comment by kevinruscoe** [comment]
Seems all you need to do is copy the files from the official Android release.

**Comment by aperfeito** [comment]
Can you do a produce a description how to do besides this rep ?

**Comment by kevinruscoe** [comment]
**download**
Download the "stable arm" version android version from http://wiki.acestream.org/wiki/index.php/Download - This has the core ARM compiled stuff
Download a linux one as well - This contains the webgui stuff, the android version doesn't have this, i don't think.

**with the android apk**
change the .apk into a .zip and unzip it. Open up the "res/raw" folder, and unzip the armeabiv7a_private_res and armeabiv7a_private_py files.

**with the linux file**
untar it, and open data/webgui

Now, with the 3 folders, just replace the older files from this repo with the new ones. use filehash to see whats changed, or even check the commit history to see what OP did when 'updating'.

**Comment by sshmanko** [comment]
Did an update, who is willing to test new version before I release it? I have no access to my rpi right now.

**Comment by kevinruscoe** [comment]
Make a PR, I'm happy to test it later on.

**Comment by kevinruscoe** [comment]
Whoops, just realised you're the author :P 

I'm willing to test. I'm at work at the moment, will be home later and I'll pull the repo down and test it.

**Comment by aperfeito** [comment]
Everything fine now ?

**Comment by kevinruscoe** [comment]
Looks fine. I've just pulled the repo and it's streaming fine.

`2019-01-11 19:19:14,879|MainThread|acestream|version=3.1.33 code=3013300 revision=dba3ac6 date=2018-09-14`

**Comment by aperfeito** [comment]
Thanks for  Everyone !

**Comment by Meikkun** [comment]
> **download** Download the "stable arm" version android version from http://wiki.acestream.org/wiki/index.php/Download - This has the core ARM compiled stuff Download a linux one as well - This contains the webgui stuff, the android version doesn't have this, i don't think.
> 
> **with the android apk** change the .apk into a .zip and unzip it. Open up the "res/raw" folder, and unzip the armeabiv7a_private_res and armeabiv7a_private_py files.
> 
> **with the linux file** untar it, and open data/webgui
> 
> Now, with the 3 folders, just replace the older files from this repo with the new ones. use filehash to see whats changed, or even check the commit history to see what OP did when 'updating'.

I've tried to follow these instructions when upgrading to 3.1.80 (latest) unsuccessfully. It seems acestream engine is now built on Python 3.8 instead of old 2.7 and the library pathing must be modified on the acestream.sh file.
My knowledge on how this chroot implementation works is absolutely zero. So not sure how much time I would need to spend on finding all the modificable paths, even considering there is nothing I have to modify on the system folder (which I honestly doubt).

Any help on this?

@sshmanko is there any chance you can do a last upgrade at least to 3.1.80 so we can keep on upgrading python 3 versions based on your work?

Thank you very much to both of you.
